version: "2.3"
services:
  demo-container-mysq-db:
    image: mysql:8
    #restart: always
    environment:
      MYSQL_USER: turreta
      MYSQL_PASSWORD: turreta+pwd!
      MYSQL_ROOT_PASSWORD: a1128f69-e6f7-4e93-a2df-3d4db6030abc
      MYSQL_DATABASE: turretadb
    ports:
      - "3306:3306"
    networks:
      - turreta_network

networks:
  turreta_network:
    driver: bridge